# Generated by Django 2.0 on 2017-12-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20171228_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpersonal',
            name='blog_description',
        ),
        migrations.RemoveField(
            model_name='blogpersonal',
            name='blog_name',
        ),
    ]
